name: test dispatch
on:
  workflow_dispatch:
    inputs:
      deploy-to-test-only:
        type: boolean
        default: false
        required: false
      skip-tests:
        type: boolean
        default: false
        required: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy to test is {{ $inputs.deploy }} with tests set to {{ $inputs.skip-tests }}
